parameters:

services:
    # ==== Paramétrage de la session ====
    sessionPdo:
        class: PDO
        arguments:
            dsn:      "mysql:host=%database_host%;port=%database_port%;dbname=SESSION"
            user:     "%database_user%"
            password: "%database_password%"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@sessionPdo", "%sessionPdo.db_options%"]

    # ==== Ajout de livrairies Twig ====
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
           - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
