#==================================================
# Default controller : page d'accueil, inscription
#==================================================
# ---- Page d'accueil ----
WebWebBundle_defaultIndex:
    path:     /
    defaults: { _controller: "WebWebBundle:Default:index" }
