#==================================================
# Security controller : page de login, inscription
#==================================================
# ---- Verification du login ----
WebWebBundle_securityCheckLogin:
    path:     /login/check
    defaults: { _controller: "WebWebBundle:Security:checkLogin" }
# ---- Login ----
WebWebBundle_securityLogin:
    path:     /login
    defaults: { _controller: "WebWebBundle:Security:login" }
# ---- Enregistrement ----
WebWebBundle_securityRegister:
    path:     /register
    defaults: { _controller: "WebWebBundle:Security:register" }
# ---- Logout ----
WebWebBundle_securityLogout:
    pattern: /logout
    defaults: { _controller: "WebWebBundle:Security:logout" }

#==================================================
# Default controller : page d'accueil, inscription
#==================================================
# ---- Page d'accueil externe  ----
WebWebBundle_defaultIndex:
    path:     /
    defaults: { _controller: "WebWebBundle:Default:index" }
# ---- Page comment ça marche  ----
WebWebBundle_defaultHowItWorks:
    path:     /hiw
    defaults: { _controller: "WebWebBundle:Default:howItWorks" }
# ---- Page A propos  ----
WebWebBundle_defaultAbout:
    path:     /about
    defaults: { _controller: "WebWebBundle:Default:about" }
# ---- Page FAQ  ----
WebWebBundle_defaultFaq:
    path:     /faq
    defaults: { _controller: "WebWebBundle:Default:faq" }
# ---- Page Contact  ----
WebWebBundle_defaultContact:
    path:     /contact
    defaults: { _controller: "WebWebBundle:Default:contact" }
# ---- Page Jobs  ----
WebWebBundle_defaultJobs:
    path:     /jobs
    defaults: { _controller: "WebWebBundle:Default:jobs" }

#=====================================
# User controller : page profile, etc
#=====================================
# ---- Page des coordonnées ----
WebWebBundle_userDetails:
    path:     /user/details
    defaults: { _controller: "WebWebBundle:User:details" }
# ---- Page de saisie du rib ----
WebWebBundle_userRib:
    path:     /user/rib
    defaults: { _controller: "WebWebBundle:User:rib" }
    requirements:
# ---- Page detail cagnotte ----
WebWebBundle_userPot:
    path:     /user/pot/{piType}/{piDate}
    defaults: { _controller: "WebWebBundle:User:pot", piType = '', piDate = ''}
# ---- Page encaissement ----
WebWebBundle_userCashIn:
    path:     /user/cash-in
    defaults: { _controller: "WebWebBundle:User:cashIn" }

#====================================
# Offer controller : page offer, etc
#====================================
# ---- Page index ----
WebWebBundle_offerIndex:
    path:     /offer/index
    defaults: { _controller: "WebWebBundle:Offer:index" }
# ---- reference graphique ----
WebWebBundle_offerGraphicStandards:
    path:     /graphicsStandards
    defaults: { _controller: "WebWebBundle:Offer:graphicsStandards" }
# ---- Page list ----
WebWebBundle_offerList:
    path:     /offer/list
    defaults: { _controller: "WebWebBundle:Offer:list" }

#=============================================
# Contact controller : page mailing list, etc
#=============================================
# ---- Page index ----
WebWebBundle_contactIndex:
    path:     /contact/index
    defaults: { _controller: "WebWebBundle:Contact:index" }
# ---- Page d'ajout ----
WebWebBundle_contactAdd:
    path:     /contact/add
    defaults: { _controller: "WebWebBundle:Contact:add" }
# ---- Abonner (menu contextuel de la page d'index) ----
WebWebBundle_contactSubscribe:
    path:     /contact/subscribe/{piContactId}
    defaults: { _controller: "WebWebBundle:Contact:subscribe" }
    requirements:
        piContactId: \d+
# ---- Désabonner (menu contextuel de la page d'index) ----
WebWebBundle_contactUnsubscribe:
    path:     /contact/unsubscribe/{piContactId}
    defaults: { _controller: "WebWebBundle:Contact:unsubscribe" }
    requirements:
        piContactId: \d+

#=======================================================
# Recommendation controller : page recommandations, etc
#=======================================================
# ---- Page index ----
WebWebBundle_recommendationIndex:
    path:     /recommendation/index
    defaults: { _controller: "WebWebBundle:Recommendation:index" }
# ---- Recommandation par Twitter ----
WebWebBundle_recommendationRecommendByTwitter:
    path:     /recommendation/recommendByTwitter/{piOfferId}/{psFrom}
    defaults: { _controller: "WebWebBundle:Recommendation:recommendByTwitter", psFrom: 'index' }
    requirements:
        piOfferId: \d+
        piFrom: \w+
# ---- Recommandation par Faceboook ----
WebWebBundle_recommendByFacebook:
    path:     /recommendation/recommendByFacebook/{piOfferId}/{psFrom}
    defaults: { _controller: "WebWebBundle:Recommendation:recommendByFacebook", psFrom: 'index' }
    requirements:
        piOfferId: \d+
        piFrom: \w+
# ---- Recommandation par Faceboook (après soummission) ----
WebWebBundle_addRecommendationByFacebook:
    path:     /recommendation/addRecommendationByFacebook/{piOfferId}/{psFrom}
    defaults: { _controller: "WebWebBundle:Recommendation:addRecommendationByFacebook", psFrom: 'index' }
    requirements:
        piOfferId: \d+
        piFrom: \w+
# ---- Recommandation par email ----
WebWebBundle_recommendationRecommendByEmail:
    path:     /recommendation/recommendByEmail/{piOfferId}/{psFrom}
    defaults: { _controller: "WebWebBundle:Recommendation:recommendByEmail", psFrom: 'index' }
    requirements:
        piOfferId: \d+
        piFrom: \w+

