parameters:
    menus:
        publisherMenu:
            label: ""
            route: ""
            pages:
                Home:
                    label: ""
                    route: WebWebBundle_offerList
                    class: RBZ_icons_home
                Offers:
                    label: publisherMenu_offers
                    route: WebWebBundle_defaultIndex
                MailingList:
                    label: publisherMenu_mailingList
                    route: WebWebBundle_defaultIndex
                # ==== Exploitation ====
                HowItWorks:
                    label: publisherMenu_howItWorks
                    route: WebWebBundle_defaultHowItWorks
                Recommendations:
                    label: publisherMenu_recommendations
                    route: WebWebBundle_defaultIndex

        publisherMenuMobile:
            label: ""
            route: ""
            pages:
                Home:
                    label: publisherMenu_home
                    route: WebWebBundle_offerList
                Offers:
                    label: publisherMenu_offers
                    route: WebWebBundle_defaultIndex
                MailingList:
                    label: publisherMenu_mailingList
                    route: WebWebBundle_defaultIndex
                # ==== Exploitation ====
                HowItWorks:
                    label: publisherMenu_howItWorks
                    route: WebWebBundle_defaultHowItWorks
                Recommendations:
                    label: publisherMenu_recommendations
                    route: WebWebBundle_defaultIndex

        publisherProfile:
            label: ""
            route: ""
            pages:
                # ===== Développement ====
                Profile:
                    label: publisherMenu_profile
                    route: WebWebBundle_userProfile

        publisherUser:
            label: ""
            route: ""
            pages:
                Particular:
                    label: publisherMenu_particulars
                    route: WebWebBundle_userParticular
                Rib:
                    label: publisherMenu_rib
                    route: WebWebBundle_userRib
                Pot:
                    label: publisherMenu_pot
                    route: WebWebBundle_userPot
                Cashin:
                    label: publisherMenu_cashin
                    route: WebWebBundle_userCashIn

        publisherFooter:
            label: ""
            route: ""
            pages:
                Offers:
                    label: publisherMenu_about
                    route: WebWebBundle_defaultAbout
                MailingList:
                    label: publisherMenu_faq
                    route: WebWebBundle_defaultFaq
                HowItWorks:
                    label: publisherMenu_contact
                    route: WebWebBundle_defaultContact
                Recommendations:
                    label: publisherMenu_jobs
                    route: WebWebBundle_defaultJobs
    # ---- Liste des identifiants api externes ----
    web.api:
        outlook:
            client_id: 000000004C139749
            client_secret: lhdePv718CLann8t1w6iyUMeKf-M-0Cm
            redirect_uri: http://rubizz.anis.natexo.com/app_dev.php/
        facebook:
            client_id: 1544677199143364
            client_secret: c66332c201f416b8423e3a457aa92e01
            redirect_uri: http://rubizz.anis.natexo.com/app_dev.php/
    # ---- Liste des tags ( offer) ----
    web.offerCategory:
            quiz: web.web.offer.list.categories.quiz
            quotation: web.web.offer.list.categories.quotation
            travel: web.web.offer.list.categories.travel
            ecommerce: web.web.offer.list.categories.ecommerce
            finances: web.web.offer.list.categories.finances
            divertissement: web.web.offer.list.categories.divertissement
            special: web.web.offer.list.categories.special
services:
    # =================== ENCODERS ===================
    # ==== Encodeur du mot de passe utilisateur ====
    web.web.encoder.user_password:
        class: Web\WebBundle\Model\Encoder\UserPasswordEncoder
        arguments: ["@natexo_tool.filter.encrypt"]

    # =================== MANAGERS ===================
    # ---- Connexion d'un utilisateur ----
    web.web.manager.user_login:
        class: Web\WebBundle\Model\Manager\UserLoginManager
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory", "@natexo_tool.filter.decrypt", "@request_stack", "@translator"]


    # ================ CONTACT VIA API ===============
    # ==== Auto Post sur Facebook ==== 
    web.web.contact.facebook:
        class: Web\WebBundle\Model\Contact\Facebook
        arguments: ["%web.api%"]
    # ==== Auto Post sur Twitter ====
    web.web.contact.twitter:
        class: Web\WebBundle\Model\Contact\Twitter
        arguments: []
    # ==== Recuperation liste de contact Outlook/hotmail ====
    web.web.contact.outlook:
        class: Web\WebBundle\Model\Contact\Outlook
        arguments: ["%web.api%"]

    # ==== Eléments de formulaires ====
    flip:
       class: Web\WebBundle\Form\Type\FlipType
       tags:
           - { name: form.type, alias: flip }

    # ==== Menu en twig ====
    web.web.twig.extension.menu:
        class: Web\WebBundle\Twig\Extension\MenuExtension
        tags:
            - { name: twig.extension }
        arguments: ["@twig.loader", "@translator", "@security.context", "%kernel.environment%", "@router", "%menus%"]
    # ---- menu listener ----
    web.web.menu.listener:
        class: Web\WebBundle\EventListener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ["@web.web.twig.extension.menu"]


    # =================== FORMS ====================
    # ==== Formulaire de login ====
    web.web.form.login_type:
        class: Web\WebBundle\Form\Security\LoginType
        tags:
            - { name: form.type, alias: WebWebLoginType }
    # ==== Formulaire d'enregistrement ====
    web.web.form.register_type:
        class: Web\WebBundle\Form\Security\RegisterType
        tags:
            - { name: form.type, alias: WebWebRegisterType }
