parameters:
    # ==== Définitions des menus ====
    menus:
        # ---- Menu principal logué ----
        rubizzMenu:
            label: ""
            route: ""
            pages:
                Home:
                    label: ""
                    route: WebWebBundle_offerIndex
                    class: RBZ_icons_home
                Offers:
                    label: rubizzMenu_offers
                    route: WebWebBundle_offerList
                MailingList:
                    label: rubizzMenu_mailingList
                    route: WebWebBundle_contactIndex
                HowItWorks:
                    label: rubizzMenu_howItWorks
                    route: WebWebBundle_defaultHowItWorks
                Recommendations:
                    label: rubizzMenu_recommendations
                    route: WebWebBundle_recommendationIndex
        # ---- Menu principal logué (version mobile) ----
        rubizzMenuMobile:
            label: ""
            route: ""
            pages:
                Home:
                    label: rubizzMenu_home
                    route: WebWebBundle_offerIndex
                Offers:
                    label: rubizzMenu_offers
                    route: WebWebBundle_offerList
                MailingList:
                    label: rubizzMenu_mailingList
                    route: WebWebBundle_defaultIndex
                HowItWorks:
                    label: rubizzMenu_howItWorks
                    route: WebWebBundle_defaultHowItWorks
                Recommendations:
                    label: rubizzMenu_recommendations
                    route: WebWebBundle_defaultIndex

        rubizzProfile:
            label: ""
            route: ""
            pages:
                # ===== Développement ====
                Profile:
                    label: rubizzMenu_profile
                    route: WebWebBundle_userDetails
                    id:    li_RBZ_headerIcoProfil
                Rib:
                    label: rubizzMenu_myRib
                    route: WebWebBundle_userRib
                    id:    li_RBZ_headerIcoRib
                Pot:
                    label: rubizzMenu_detailPot
                    route: WebWebBundle_userPot
                    id:    li_RBZ_headerIcoPot
                Cashin:
                    label: rubizzMenu_cashin
                    route: WebWebBundle_userCashIn
                    id:    li_RBZ_headerIcoCash
                Logout:
                    label: rubizzMenu_logout
                    route: WebWebBundle_securityLogout
                    id:    li_RBZ_headerIcoLogout

        rubizzUser:
            label: ""
            route: ""
            pages:
                Particular:
                    label: rubizzMenu_details
                    route: WebWebBundle_userDetails
                Rib:
                    label: rubizzMenu_rib
                    route: WebWebBundle_userRib
                Pot:
                    label: rubizzMenu_pot
                    route: WebWebBundle_userPot
                Cashin:
                    label: rubizzMenu_cashin
                    route: WebWebBundle_userCashIn

        rubizzFooter:
            label: ""
            route: ""
            pages:
                Offers:
                    label: rubizzMenu_about
                    route: WebWebBundle_defaultAbout
                MailingList:
                    label: rubizzMenu_faq
                    route: WebWebBundle_defaultFaq
                Contact:
                    label: rubizzMenu_contact
                    route: WebWebBundle_defaultLogoutContact
                    id: li_RBZ_contactPopupCall
                    hrefbis: true
#                Recommendations:
#                    label: rubizzMenu_jobs
#                    route: WebWebBundle_defaultJobs

        rubizzFooterLogout:
            label: ""
            route: ""
            pages:
                Offers:
                    label: rubizzMenu_about
                    route: WebWebBundle_defaultLogoutAbout
                MailingList:
                    label: rubizzMenu_faq
                    route: WebWebBundle_defaultLogoutFaq
                HowItWorks:
                    label: rubizzMenu_contact
                    route: WebWebBundle_defaultLogoutContact
                    id: li_RBZ_contactPopupCall
                    hrefbis: true
#                Recommendations:
#                    label: rubizzMenu_jobs
#                    route: WebWebBundle_defaultJobs

    # ---- Liste des identifiants api externes ----
    web.api:
        outlook:
            client_id: 000000004C139749
            client_secret: lhdePv718CLann8t1w6iyUMeKf-M-0Cm
            redirect_uri: http://rubizz.anis.natexo.com/app_dev.php/
        facebook:
            fr:
                client_id: 1544677199143364
                client_secret: c66332c201f416b8423e3a457aa92e01
            us:
                client_id: 840839625988357
                client_secret: 9264be342502bbb7107932c7793ef358
    # ---- Liste des tags ( offer) ----
    web.offer_category:
        sweepstake:    web.web.offer.list.categories.sweepstake
        estimate:      web.web.offer.list.categories.quotation
        travel:        web.web.offer.list.categories.travel
        e-commerce:    web.web.offer.list.categories.ecommerce
        finance:       web.web.offer.list.categories.finances
        untertainment: web.web.offer.list.categories.divertissement
        special-offer: web.web.offer.list.categories.special
services:
    # =================== MODEL ===================
    # ==== USER ====
    # ---- Connexion d'un utilisateur ----
    web.web.model.user.user_logger:
        class: Web\WebBundle\Model\User\UserLogger
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory", "@natexo_tool.filter.decrypt", "@request_stack", "@translator"]

    # ==== ENCODERS ====
    # ---- Encodeur du mot de passe utilisateur ----
    web.web.model.encoder.user_password:
        class: Web\WebBundle\Model\Encoder\UserPasswordEncoder
        arguments: ["@natexo_tool.filter.encrypt"]

    # ==== TRACKING ====
    # ---- Chainage des modèles ----
    web.web.model.tracking.tracking_chain:
        class: Web\WebBundle\Model\Tracking\TrackingChain
    # ---- Modèle CAKE ----
#    admin.rubizz.offerTrackingCake:
#        class: AdminRubizz\RubizzBundle\Model\Offer\Stat\CakeStat
#        arguments: ["%admin.rubizz.cake%", "@doctrine.orm.rubizzRubizz_entity_manager"]
#        tags:
#            - { name: offer-stat, alias: cake }
    # ---- Gestion du tracking ----
    web.web.model.tracking.tracking:
        class: Web\WebBundle\Model\Tracking\Tracking
        arguments: ["@doctrine.orm.entity_manager", "@natexo_tool.filter.encrypt", "@natexo_tool.filter.decrypt"]

    # ==== CONTACT ====
    # ---- Auto Post sur Facebook ----
    web.web.model.contact.facebook:
        class: Web\WebBundle\Model\Contact\Facebook
        arguments: ["%web.api%"]
    # ---- Auto Post sur Twitter ----
    web.web.model.contact.twitter:
        class: Web\WebBundle\Model\Contact\Twitter
        arguments: []
    # ---- Récuperation liste de contact Outlook/hotmail ----
    web.web.model.contact.outlook:
        class: Web\WebBundle\Model\Contact\Outlook
        arguments: ["@request_stack", "@router", "@doctrine.orm.entity_manager", "@natexo_tool.filter.decrypt"]
    web.web.model.contact.yahoo:
        class: Web\WebBundle\Model\Contact\YahooModel
        arguments: ["@request_stack", "@router", "@natexo_tool.filter.decrypt", "@doctrine.orm.entity_manager"]
    web.web.model.contact.gmail:
        class: Web\WebBundle\Model\Contact\Gmail
        arguments: ["@request_stack", "@router", "@doctrine.orm.entity_manager", "@natexo_tool.filter.decrypt"]
    # ---- Model d'ajout de contact ----
    web.web.model.contact.email:
        class: Web\WebBundle\Model\Contact\Email
        arguments: ["@doctrine.orm.entity_manager"]

    # ==== RESPONSE ====
    # ---- Img vide pour tracking ----
    web.web.model.response.empty_img_response:
        class: Web\WebBundle\Model\Response\EmptyImgResponse

    # =================== TWIG ===================
    # ==== MENU ====
    # ---- Menu en twig ----
    web.web.twig.extension.menu_extension:
        class: Web\WebBundle\Twig\Extension\MenuExtension
        tags:
            - { name: twig.extension }
        arguments: ["@twig.loader", "@translator", "@security.context", "%kernel.environment%", "@router", "%menus%"]

    # =================== EVENT LISTENER ===================
    # ==== MENU ====
    # ---- Menu listener ----
    web.web.event_listener.controller_listener:
        class: Web\WebBundle\EventListener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ["@web.web.twig.extension.menu_extension"]


    # =================== FORM ====================
    # ==== Éléments de formulaire ====
    # ---- Flip ----
    flip:
       class: Web\WebBundle\Form\Type\FlipType
       tags:
           - { name: form.type, alias: flip }

    # ==== Security ====
    # ---- Formulaire de login ----
    web.web.form.login_type:
        class: Web\WebBundle\Form\Security\LoginType
        tags:
            - { name: form.type, alias: WebWebLoginType }
    # ---- Formulaire d'enregistrement ----
    web.web.form.register_type:
        class: Web\WebBundle\Form\Security\RegisterType
        tags:
            - { name: form.type, alias: WebWebRegisterType }

    # ==== User ====
    # ---- Formulaire RIB User ----
    web.web.form.user_bic_type:
        class: Web\WebBundle\Form\User\UserBicType
        tags:
            - { name: form.type, alias: WebWebUserBicType }
        arguments: ["@natexo_tool.filter.encrypt", "@natexo_tool.filter.decrypt"]
    # ---- Sous Formulaire RIB User ----
    web.web.form.bic_type:
        class: Web\WebBundle\Form\User\BicType
        tags:
            - { name: form.type, alias: WebWebBicType }
    # ---- Saisie des coordonnées ----
    web.web.form.user_details_type:
        class: Web\WebBundle\Form\User\UserDetailsType
        tags:
            - { name: form.type, alias: WebWebUserDetailsType }

    # ==== Contact ====
    # ---- Formulaire de recherche ----
    web.web.form.contact_search_type:
        class: Web\WebBundle\Form\Contact\ContactSearchType
        tags:
            - { name: form.type, alias: WebWebContactSearchType }
    # ---- Formulaire d'ajout de contact ----
    web.web.form.contact_add_type:
        class: Web\WebBundle\Form\Contact\ContactAddType
        tags:
            - { name: form.type, alias: WebWebContactAddType }
    # ---- Formulaire d'ajout de contact ----
    web.web.form.short_contact_type:
        class: Web\WebBundle\Form\Contact\ShortContactType
        tags:
            - { name: form.type, alias: WebWebShortContactType }


    # ==== Formulaire de Contact ====
    web.web.form.contact_type:
        class: Web\WebBundle\Form\Defaul\ContactType
        tags:
            - { name: form.type, alias: WebWebContactType }


