Web\WebBundle\Entity\User:
    properties:
        email:
            - Email: { groups: [register], message: "rubizz.web.web.security.invalid_email" }
        password:
            - NotBlank: { groups: [register], message: "rubizz.web.web.security.pwd.notblank" }